# Task 1:

# 1.Write a function to compute 5/0 and use try/except to catch the exceptions.

In [1]:
try:
    x=5/0
except ZeroDivisionError:
    print("Error divide by zero")

Error divide by zero


# 2.Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].

# Hint: Subject,Verb and Object should be declared in the program as shown below.
    
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [2]:
subjects=["Americans","Indians"]
verbs=["Play","Watch"]
objects=["Baseball","Cricket"]
sentence=[sub+" "+ver+" "+obj for sub in subjects for ver in verbs for obj in objects]
for i in sentence:
    print(i)

Americans Play Baseball
Americans Play Cricket
Americans Watch Baseball
Americans Watch Cricket
Indians Play Baseball
Indians Play Cricket
Indians Watch Baseball
Indians Watch Cricket


# Task 2:

# 1.Write a function so that the columns of the output matrix are powers of the input vector.

# The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

In [5]:
import numpy as np
x=np.array([1,2,3,5])
N=3
ar=np.vander(x,N)
ar

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [8]:
a=np.column_stack([x**(N-1-i) for i in range(N)])

In [10]:
a

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [12]:
X=np.array([1,2,3,5])
np.vander(X)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [16]:
np.vander(x,increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])